src/Server/TrainingLog/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainingLog.Factory;
using TrainingLog.Repository.Interface;
using TrainingLog.Model;

namespace TrainingLog.Controllers
{
    public class ExerciseController : Controller
    {
        // GET: Exercise
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Statistics()
        {
            return View();
        }

        public ActionResult List()
        {
            RepositoryFactory factory = new RepositoryFactory();
            IExerciseRepository repo = factory.GetExerciseRepo();

            List<Exercise> exercises = repo.GetExcercises();

            ViewBag.Exercises = exercises;

            return View();
        }

        // GET: Exercise/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Exercise/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Exercise/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Exercise/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Exercise/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Exercise/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Exercise/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Server/TrainingLog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrainingLog.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Server/TrainingLog/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrainingLog.Controllers
{
    public class UserProfileController : Controller
    {
        // GET: UserProfile
        public ActionResult UserInfo()
        {
            return View();
        }
    }
}

src/Server/TrainingLog/Views/Exercise/Details.cshtml
@model TrainingLog.Models.Exercise

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Exercise</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/Server/TrainingLog/Views/Exercise/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>List</h2>

    <table class="table">

    @foreach (var exercise in ViewBag.Exercises)
    {
        <tr>
            <td>@exercise.ID</td>
            <td>@exercise.LengthInTime</td>
            <td>@exercise.Type</td>
            <td>@exercise.LentghInMeters</td>
            <td>@exercise.Name</td>
            <td>@exercise.Comment</td>
        </tr>
    }
</table>

src/Server/TrainingLog/Views/Exercise/Statistics.cshtml
@{
    ViewBag.Title = "Statistics";
}

<h2>Statistics</h2>

src/Server/TrainingLog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h2>My training log</h2>
    <p>Less is more.</p>
</div>

@Html.Partial("ExerciseList")

src/Server/TrainingLog/Views/Shared/ExerciseList.cshtml
<div class="container">

    <div style="margin-top:15px">
        <div class="row">
            <div class="col-sm-1">
                <img src="~/Pics/002-running.png" class="img-responsive" />
            </div>
            <div class="col-sm-5">
                <div class="row">
                    <div class="col-sm-8"><P style="font-size:large;">Afternoon Run <span class="label label-info">New</span></P></div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Distance: 19,1km</div>
                    <div class="col-sm-4">Speed: 6:12/km</div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Time: 2:31:15</div>
                    <div class="col-sm-4">HR: 133</div>
                </div>
                <div class="row collapse" id="map1">
                    <div class="col-sm-8">
                        <div id="map" style="height:200px; width:400px"></div>
                        <script>
                            function initMap() {
                                var uluru = { lat: -25.363, lng: 131.044 };
                                var map = new google.maps.Map(document.getElementById('map'), {
                                    zoom: 4,
                                    center: uluru
                                });
                                var marker = new google.maps.Marker({
                                    position: uluru,
                                    map: map
                                });
                            }
                        </script>
                        <script async defer
                                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCFf0roKIL_NNvmLYoSXDcd8CIMXZmVS_Y&callback=initMap">
                        </script>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <div class="btn-group">
                            <button data-toggle="collapse" data-target="#map1" class="btn btn-danger btn-sm">Map</button>
                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#pics3">Photos</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="margin-top:15px">
        <div class="row">
            <div class="col-sm-1">
                <img src="~/Pics/001-transport.png" class="img-responsive" />
            </div>
            <div class="col-sm-5">
                <div class="row">
                    <div class="col-sm-4"><P style="font-size:large;">Afternoon Ride</P></div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Distance: 19,1km</div>
                    <div class="col-sm-4">Speed: 6:12/km</div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Time: 2:31:15</div>
                    <div class="col-sm-4">HR: 133</div>
                </div>
            </div>
        </div>
    </div>
    <div style="margin-top:15px">
        <div class="row">
            <div class="col-sm-1">
                <img src="~/Pics/002-running.png" class="img-responsive" />
            </div>
            <div class="col-sm-5">
                <div class="row">
                    <div class="col-sm-4"><P style="font-size:large;">Afternoon Run</P></div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Distance: 19,1km</div>
                    <div class="col-sm-4">Speed: 6:12/km</div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Time: 2:31:15</div>
                    <div class="col-sm-4">HR: 133</div>
                </div>
            </div>
        </div>
    </div>
    <div style="margin-top:15px">
        <div class="row">
            <div class="col-sm-1">
                <img src="~/Pics/002-running.png" class="img-responsive" />
            </div>
            <div class="col-sm-5">
                <div class="row">
                    <div class="col-sm-4"><P style="font-size:large;">Afternoon Run</P></div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Distance: 19,1km</div>
                    <div class="col-sm-4">Speed: 6:12/km</div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Time: 2:31:15</div>
                    <div class="col-sm-4">HR: 133</div>
                </div>
            </div>
        </div>
    </div>
    <div style="margin-top:15px">
        <div class="row">
            <div class="col-sm-1">
                <img src="~/Pics/001-transport.png" class="img-responsive" />
            </div>
            <div class="col-sm-5">
                <div class="row">
                    <div class="col-sm-4"><P style="font-size:large;">Afternoon Ride</P></div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Distance: 19,1km</div>
                    <div class="col-sm-4">Speed: 6:12/km</div>
                </div>
                <div class="row">
                    <div class="col-sm-4">Time: 2:31:15</div>
                    <div class="col-sm-4">HR: 133</div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="pics3" class="modal fade" role="dialog" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"> <button class="close" aria-label="close" data-dismiss="modal">&times;</button></div>
            <div class="modal-body">
                @Html.Partial("PictureCarousel")
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#map1").on('shown.bs.collapse', function () {
            initMap();
        });
    });

</script>

src/Server/TrainingLog/Views/Shared/Login.cshtml
<div id="login" class="modal fade" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input id="email" type="text" class="form-control" name="email" placeholder="Email">
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                        <div class="modal-footer"><button class="btn btn-alert-danger">Login</button></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> 

src/Server/TrainingLog/Views/Shared/PictureCarousel.cshtml
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="/pics/exer1.jpg" alt="Nuts1">
        </div>

        <div class="item">
            <img src="/pics/exer2.jpg" alt="Nuts1">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

src/Server/TrainingLog/Views/Shared/SignUp.cshtml
<div id="signUp" class="modal fade" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header"><button class="close" data-dismiss="modal">&times;</button> </div>
                <div class="modal-body">
                    <form>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input id="email" type="text" class="form-control" name="email" placeholder="Email">
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                    </form>
                </div>
                <div class="modal-footer"><button class="btn btn-alert-danger">Register</button></div>
            </div>
        </div>
    </div>
</div>

src/Server/TrainingLog/Views/Shared/TenDaysStats.cshtml
<div class="jumbotron">
    <h3>Statistics of last 10 days</h3>
    <div style="margin-top:25px"><h4>Running</h4></div>
    <div class="row">
        <div class="col-lg-3">Distance: 150km</div>
        <div class="col-lg-3">AVG Speed: 5:25min/km</div>
        <div class="col-lg-3">Number of excercises: 4</div>
    </div>
    <div class="row">
        <div class="col-lg-3">AGV HR: 140</div>
        <div class="col-lg-3">Climb: 1500m</div>
        <div class="col-lg-3">Training effect: 1500</div>
    </div>

    <div style="margin-top:25px"><h4>Cycling</h4></div>
    <div class="row">
        <div class="col-lg-3">Distance: 25</div>
        <div class="col-lg-3">AVG Speed: 22km/h</div>
        <div class="col-lg-3">Number of excercises: 3</div>
    </div>
    <div class="row">
        <div class="col-lg-3">AGV HR: 120</div>
        <div class="col-lg-3">Climb: 250m</div>
        <div class="col-lg-3">Training effect: 120</div>
    </div>
    <div style="margin-top:25px">
        <h4>Overall training effect 1620</h4>
        <h4>State of recovery: fully recovered</h4>
    </div>
</div>

src/Server/TrainingLog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title of My Training Log</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">My Training Log</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Home","Index","Home")</li>
                    <li>@Html.ActionLink("Training","List", "Exercise")</li>
                    <li>@Html.ActionLink("Statistics","Statistics","Exercise")</li>
                    <li>@Html.ActionLink("My Profile","UserInfo","UserProfile")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right" style="position: relative; display: block; padding: 10px 15px;">
                    <li><button class="btn-link" data-toggle="modal" data-target="#signUp"><span class="glyphicon glyphicon-user"></span> Sign Up</button></li>
                    <li><button class="btn-link" data-toggle="modal" data-target="#login"><span class="glyphicon glyphicon-log-in"></span> Login</button></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    @Html.Partial("Login")
    @Html.Partial("SignUp")
</body>
</html>

src/Server/TrainingLog/Views/UserProfile/UserInfo.cshtml
@{
    ViewBag.Title = "UserProfile";
}

<h2>UserProfile</h2>